name: Build

on:
  workflow_dispatch: # To have the ability to run the workflow manually

  push:
    branches: [main]

jobs:
  ReleaseVersionPixelfed:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build ./Pixelfed --tag lnadev/pixelfed-autoupload:${{ github.run_number }}

      - name: Push the image to dockerhub
        run: docker push lnadev/pixelfed-autoupload:${{ github.run_number }}

  ReleaseVersionBluesky:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build ./Bluesky --tag lnadev/bluesky-autoupload:${{ github.run_number }}

      - name: Push the image to dockerhub
        run: docker push lnadev/bluesky-autoupload:${{ github.run_number }}

  ReleaseVersionInstagram:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build ./Instagram --tag lnadev/instagram-autoupload:${{ github.run_number }}

      - name: Push the image to dockerhub
        run: docker push lnadev/instagram-autoupload:${{ github.run_number }}